export const APPLY_ERROR = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  ROLE_NOT_STUDENT: 'ROLE_NOT_STUDENT',
  RESUME_REQUIRED: 'RESUME_REQUIRED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  DUPLICATE_APPLICATION: 'DUPLICATE_APPLICATION',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  INVALID_RESUME_FILE: 'INVALID_RESUME_FILE',
  APPLICATION_INSERT_FAILED: 'APPLICATION_INSERT_FAILED',
} as const

export type ApplyErrorCode = (typeof APPLY_ERROR)[keyof typeof APPLY_ERROR]

export function isDuplicateApplicationConstraintError(error: { code?: string } | null | undefined) {
  return error?.code === '23505'
}
