insert into public.skills (slug, label, category)
values
  ('javascript', 'JavaScript', 'Software'),
  ('typescript', 'TypeScript', 'Software'),
  ('react', 'React', 'Software'),
  ('node-js', 'Node.js', 'Software'),
  ('python', 'Python', 'Software'),
  ('java', 'Java', 'Software'),
  ('c-plus-plus', 'C++', 'Software'),
  ('git', 'Git', 'Software'),
  ('rest-apis', 'REST APIs', 'Software'),
  ('graphql', 'GraphQL', 'Software'),
  ('docker', 'Docker', 'Software'),
  ('aws', 'AWS', 'Software'),
  ('sql', 'SQL', 'Data'),
  ('postgresql', 'PostgreSQL', 'Data'),
  ('microsoft-excel', 'Microsoft Excel', 'Data'),
  ('google-sheets', 'Google Sheets', 'Data'),
  ('tableau', 'Tableau', 'Data'),
  ('power-bi', 'Power BI', 'Data'),
  ('statistics', 'Statistics', 'Data'),
  ('machine-learning', 'Machine Learning', 'Data'),
  ('data-visualization', 'Data Visualization', 'Data'),
  ('communication', 'Communication', 'Business'),
  ('project-management', 'Project Management', 'Business'),
  ('product-management', 'Product Management', 'Business'),
  ('market-research', 'Market Research', 'Business'),
  ('crm', 'CRM', 'Business'),
  ('operations-analysis', 'Operations Analysis', 'Business'),
  ('strategy', 'Strategy', 'Business'),
  ('presentation-skills', 'Presentation Skills', 'Business'),
  ('seo', 'SEO', 'Marketing'),
  ('content-marketing', 'Content Marketing', 'Marketing'),
  ('social-media-marketing', 'Social Media Marketing', 'Marketing'),
  ('email-marketing', 'Email Marketing', 'Marketing'),
  ('google-analytics', 'Google Analytics', 'Marketing'),
  ('paid-search', 'Paid Search', 'Marketing'),
  ('copywriting', 'Copywriting', 'Marketing'),
  ('financial-modeling', 'Financial Modeling', 'Finance'),
  ('valuation', 'Valuation', 'Finance'),
  ('accounting', 'Accounting', 'Finance'),
  ('corporate-finance', 'Corporate Finance', 'Finance'),
  ('budgeting', 'Budgeting', 'Finance'),
  ('forecasting', 'Forecasting', 'Finance'),
  ('investment-analysis', 'Investment Analysis', 'Finance'),
  ('quickbooks', 'QuickBooks', 'Finance'),
  ('figma', 'Figma', 'Design'),
  ('ui-design', 'UI Design', 'Design'),
  ('ux-research', 'UX Research', 'Design'),
  ('wireframing', 'Wireframing', 'Design'),
  ('prototyping', 'Prototyping', 'Design'),
  ('adobe-photoshop', 'Adobe Photoshop', 'Design'),
  ('adobe-illustrator', 'Adobe Illustrator', 'Design'),
  ('branding', 'Branding', 'Design'),
  ('user-testing', 'User Testing', 'Design')
on conflict (slug) do update
set
  label = excluded.label,
  category = excluded.category;

with alias_map(alias, slug) as (
  values
    ('javascript', 'javascript'),
    ('js', 'javascript'),
    ('typescript', 'typescript'),
    ('ts', 'typescript'),
    ('react', 'react'),
    ('reactjs', 'react'),
    ('node', 'node-js'),
    ('nodejs', 'node-js'),
    ('node-js', 'node-js'),
    ('python', 'python'),
    ('py', 'python'),
    ('java', 'java'),
    ('c++', 'c-plus-plus'),
    ('cpp', 'c-plus-plus'),
    ('git', 'git'),
    ('rest', 'rest-apis'),
    ('restapi', 'rest-apis'),
    ('restapis', 'rest-apis'),
    ('graphql', 'graphql'),
    ('docker', 'docker'),
    ('aws', 'aws'),
    ('sql', 'sql'),
    ('postgres', 'postgresql'),
    ('postgresql', 'postgresql'),
    ('excel', 'microsoft-excel'),
    ('microsoft-excel', 'microsoft-excel'),
    ('googlesheets', 'google-sheets'),
    ('google-sheets', 'google-sheets'),
    ('g-sheets', 'google-sheets'),
    ('tableau', 'tableau'),
    ('powerbi', 'power-bi'),
    ('power-bi', 'power-bi'),
    ('statistics', 'statistics'),
    ('stats', 'statistics'),
    ('machinelearning', 'machine-learning'),
    ('ml', 'machine-learning'),
    ('data-viz', 'data-visualization'),
    ('dataviz', 'data-visualization'),
    ('communication', 'communication'),
    ('pm', 'project-management'),
    ('project-management', 'project-management'),
    ('product-management', 'product-management'),
    ('market-research', 'market-research'),
    ('crm', 'crm'),
    ('operations', 'operations-analysis'),
    ('operations-analysis', 'operations-analysis'),
    ('strategy', 'strategy'),
    ('presentation', 'presentation-skills'),
    ('presentation-skills', 'presentation-skills'),
    ('seo', 'seo'),
    ('content-marketing', 'content-marketing'),
    ('social-media', 'social-media-marketing'),
    ('social-media-marketing', 'social-media-marketing'),
    ('email-marketing', 'email-marketing'),
    ('googleanalytics', 'google-analytics'),
    ('google-analytics', 'google-analytics'),
    ('paid-search', 'paid-search'),
    ('copywriting', 'copywriting'),
    ('financial-modeling', 'financial-modeling'),
    ('fin-modeling', 'financial-modeling'),
    ('valuation', 'valuation'),
    ('accounting', 'accounting'),
    ('corporate-finance', 'corporate-finance'),
    ('budgeting', 'budgeting'),
    ('forecasting', 'forecasting'),
    ('investment-analysis', 'investment-analysis'),
    ('quickbooks', 'quickbooks'),
    ('figma', 'figma'),
    ('ui', 'ui-design'),
    ('ui-design', 'ui-design'),
    ('ux', 'ux-research'),
    ('ux-research', 'ux-research'),
    ('wireframes', 'wireframing'),
    ('wireframing', 'wireframing'),
    ('prototyping', 'prototyping'),
    ('photoshop', 'adobe-photoshop'),
    ('adobe-photoshop', 'adobe-photoshop'),
    ('illustrator', 'adobe-illustrator'),
    ('adobe-illustrator', 'adobe-illustrator'),
    ('branding', 'branding'),
    ('user-testing', 'user-testing')
)
insert into public.skill_aliases (alias, skill_id)
select am.alias, s.id
from alias_map am
join public.skills s on s.slug = am.slug
on conflict (alias) do update
set skill_id = excluded.skill_id;
